[workspace]

members = [
  "api",
  "ui",
]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
# [[bin]]
# name = "dalia"
# path = "api/src/main.rs"

# [dependencies]
# actix-web = "4.3.1"

